/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jm1_1;

import java.awt.Image;
import java.awt.TextField;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import jm.Dominio.Jm11;
import jmRepositorio.Jm1repository1;

/**
 *
 * @author a
 */
public class Datos extends javax.swing.JInternalFrame {

  Jm1repository1 jmRepositorio =new Jm1repository1();
  
    public Datos() {
        initComponents();
        
        /*this.setExtendedState(Datos.MAXIMIZED_BOTH);
         ImageIcon i = new ImageIcon("src/ImagenesJuego/76076.jpg");
        Icon ico = new ImageIcon(i.getImage().getScaledInstance( jLabel5.getWidth(),  jLabel5.getHeight(), Image.SCALE_DEFAULT));
        jLabel5.setIcon(ico);*/
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Login = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Contra1 = new javax.swing.JPasswordField();
        txtConf = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Datos Usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Confirmar Contr.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        Nombre.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Nombre.setToolTipText("Maximo 30 Digitos");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 161, -1));

        Login.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(51, 51, 51));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LoginKeyTyped(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 161, -1));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        Contra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contra1ActionPerformed(evt);
            }
        });
        Contra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Contra1KeyTyped(evt);
            }
        });
        getContentPane().add(Contra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, -1));

        txtConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfActionPerformed(evt);
            }
        });
        txtConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfKeyTyped(evt);
            }
        });
        getContentPane().add(txtConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 160, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesJuego/xvvc35eysco.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
 // TODO add your handling code here:
 
    }//GEN-LAST:event_LoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 Nombre.setText("");
		Login.setText("");
		Contra1.setText("");
		txtConf.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyTyped
 char c=evt.getKeyChar();
				if(Character.isDigit(c)){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Solo puede Ingresar Letras");
			}
				if(Login.getText().length()==8){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Excedio limite");	
				}         // TODO add your handling code here:
    }//GEN-LAST:event_LoginKeyTyped

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
char c=evt.getKeyChar();
				if(Character.isDigit(c)){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Solo puede Ingresar letras");
				}
				if(Nombre.getText().length()==30){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Excedio limite");	
				}        // TODO add your handling code here:
    }//GEN-LAST:event_NombreKeyTyped

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
/*String letra=Nombre.getText();
if(letra.length()>0){
char primeraletra=letra.charAt(0);
letra=Character.toUpperCase(primeraletra)+letra.substring(1, letra.length());
Nombre.setText(letra);
}
char[] caracteres = letra.toCharArray();
caracteres[0] = Character.toUpperCase(caracteres[0]);
for (int i = 0; i < letra.length()- 2; i++) 
    // Es 'palabra'
    if (caracteres[i] == ' ' || caracteres[i] == '.' || caracteres[i] == ',')
      // Reemplazamos
      caracteres[i + 1] = Character.toUpperCase(caracteres[i + 1]);
Nombre.setText(letra);*/
// TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       boolean[] field = new boolean[4];
       boolean r=false;
       String nombre =(Nombre.getText());
       String login =(Login.getText());
       int contraseña = Integer.parseInt(Contra1.getText());
       int recontraseña = Integer.parseInt(txtConf.getText());
      
       if(contraseña==recontraseña){
          Jm11 juego = new Jm11(0,nombre,login,contraseña,recontraseña);
   jmRepositorio.ingresar(juego);
        
       JOptionPane.showMessageDialog(null,"USUARIO "+ " "+nombre+" " +"HA SIDO REGISTRADO");  
       }else{
          JOptionPane.showMessageDialog(null,"claves incorrectas no son iguales :(");
       }

       dispose();
       /*Jm1 juego = new Jm1(0,nombre,login,contraseña,recontraseña);
       jmRepositorio.ingresar(juego);
        
 JOptionPane.showMessageDialog(null,"USUARIO "+ " "+nombre+" " +"HA SIDO REGISTRADO");*/
        
        
   
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Contra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contra1ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_Contra1ActionPerformed

    private void Contra1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Contra1KeyTyped
      char c=evt.getKeyChar();
				if(Character.isLetter(c)& c !=evt.VK_BACK_SPACE){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Solo puede Ingresar Numeros");
			}
				if(Contra1.getText().length()==8){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Excedio limite");	
				}    // TODO add your handling code here:
    }//GEN-LAST:event_Contra1KeyTyped

    private void txtConfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfKeyTyped
char c=evt.getKeyChar();
				if(Character.isLetter(c)& c !=evt.VK_BACK_SPACE){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Solo puede Ingresar Numeros");
			}
				if(txtConf.getText().length()==8){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Excedio limite");	
				}          // TODO add your handling code here:
    }//GEN-LAST:event_txtConfKeyTyped

    private void txtConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contra1;
    private javax.swing.JTextField Login;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPasswordField txtConf;
    // End of variables declaration//GEN-END:variables
}
