/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jm1_1;


import java.awt.Image;
import java.sql.PreparedStatement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jm.Dominio.Jm11;
import static jm1_1.MainJf.Juego;
import jmRepositorio.Jm1repository1;

import jmRepositorio.LoginMetodo;

/**
 *
 * @author PC1
 */
public class Usuario extends javax.swing.JFrame {
static LoginMetodo lo = new LoginMetodo();
    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
         ImageIcon i = new ImageIcon("src/ImagenesJuego/76076.jpg");
        Icon ico = new ImageIcon(i.getImage().getScaledInstance( usuario.getWidth(),  usuario.getHeight(), Image.SCALE_DEFAULT));
        usuario.setIcon(ico);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();
        usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 94, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("CLAVE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 147, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("INICIAR SESION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 91, 221, -1));

        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("VAMOS A JUGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 228, -1, -1));

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveKeyTyped(evt);
            }
        });
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 220, -1));
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        Preguntas_n2 pre = new Preguntas_n2();
          pre.setVisible(true);
          dispose(); 
       
       
        /*String login = (this.txtUsuario.getText());
     // String contra= (this.txtpasword.getText());
        Jm1 jm=new Jm1(login);
         String nombre=lo.login(login).getLogin();
      // String nombre=lo.Login(usuario).getUsuario();
     // String logi = lo.login(login).getLogin();
      //String cont = lo.login(login).getContraseña();
      String SSQL="SELECT * FROM usuarios WHERE usuario='"+login+"' AND clave=sha1('"+nombre+"')";
      
      if(txtUsuario.getText().equals("")){
          JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA INCORRECTA");   
        }
      else {
          JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA CORRECTA");
      
          Preguntas pre = new Preguntas();
          pre.setVisible(true);
          dispose();
      }*/
//aqui tienes q poner la validacion para poder ingresar 
        
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
    char c=evt.getKeyChar();
				if(Character.isDigit(c)){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Solo puede Ingresar Letras");
			}
				if(txtUsuario.getText().length()==8){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Excedio limite");	
				}          // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyTyped
     char c=evt.getKeyChar();
				if(Character.isLetter(c)& c !=evt.VK_BACK_SPACE){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Solo puede Ingresar Numeros");
			}
				if(txtClave.getText().length()==8){
					evt.consume();
					JOptionPane.showMessageDialog(null, "Excedio limite");	
				}         // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPasswordField txtClave;
    public static javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
